### ISSUE TITLE
AttributeError: module 'torchvision.transforms' has no attribute 'InterpolationMode'

### ISSUE THREAD

**Issue by AnttiKarlsson** [agaldran/lwnet#4]
When running the scripts, I get an error: 

`Traceback (most recent call last):
  File "predict_one_image.py", line 8, in <module>
    from utils import paired_transforms_tv04 as p_tr
  File "/home/jovyan/work/retina-segment/utils/paired_transforms_tv04.py", line 37, in <module>
    T.InterpolationMode.NEAREST: 'PIL.Image.NEAREST',
AttributeError: module 'torchvision.transforms' has no attribute 'InterpolationMode'`

Looking at the history, it seems that these lines were changed a while ago, so did that break something, or should some of the environment libraries be changed to different versions?

**Comment by agaldran** [comment]
Hi @AnttiKarlsson ,

You are right, I did change the transforms in `utils/paired_transforms_tv04.py` so that they would work with newer versions of `torchvision`, and as a result, if you now create your environment using the provided `requirements.txt` file, it installs the old `torchvision` and then it crashes. 

The fix is, you just need to update to the latest version of `torchvision` and it should stop complaining, I think. I just created a conda environment from scratch with the default latest available versions of torch, torchvision, pandas, tqdm, scikit-image, scikit-learn, and it seems to run smoothly. Please let me know if you are unable to run the code.

Cheers,

Adrian

**Comment by AnttiKarlsson** [comment]
Oh, great, thank you! I ran the code by modifying the utils to the previous version. I'll try updating torchvision and then use this newer version.
